## 웹 페이지 자동수집

### 셀레니움

- 웹 브라우저를 자동으로 제어하는 파이썬 라이브러리(패키지)
- 기능
    - 브라우저 실행
    - 웹 페이지 로드(접속)
    - 입력창에 글자 입력(아이디, 패스워드 등)
    - 버튼 클릭
    - 페이지 이동
    - 화면에 표시된 텍스트 추출
    - 특정 이미지 저장 / 화면 스크린 캡처
    - 반복 자동화

- 정적인 HTML은 Beautifulsoup4, request 패키지로 수집가능
- 동적인 웹화면은 Selenium이 강력함 / 정적인 웹페이지도 가능

#### 웹브라우저 실행

In [1]:
# 셀레니움 패키지 로드
from selenium import webdriver
import pandas as pd

In [2]:
driver = webdriver.Chrome()

driver.get(f'http://www.naver.com')

In [3]:
# 웹브라우저 종료

driver.quit()

#### 웹 페이지 스크래핑 실습

In [4]:
driver = webdriver.Chrome()

driver.get(f'http://127.0.0.1:5500/chapt04/products.html')

##### 요소찾기

- 주요 요소 찾기 방식
    - `By.ID` : ID로 찾기
    - `By.CLASS_NAME` : class명으로 찾기
    - `By.TAG_NAME` : 태그명으로 찾기
    - `By.CSS_SELECTOR` : CSS 선택자 방법으로 찾기
    - `By.XPATH` : XPath로 찾기

In [5]:
# CSS 선택자로 요소찾는 함수용 패키지 내 클래스 로드

from selenium.webdriver.common.by import By

In [6]:
title = driver.find_element(By.ID, 'title')

title.text

'상품목록'

In [7]:
# 페이지 내 여러 요소를 동시에 추출

products = driver.find_elements(By.CLASS_NAME, 'product')

len(products)

3

In [8]:
for product in products:
    print(product.text)

키보드 30000
마우스 15000
모니터 250000

##### CSS 선택자료 요소 추출

In [9]:
products = driver.find_elements(By.CSS_SELECTOR, '.product')

for product in products:
    print(product)
    name = product.find_element(By.CSS_SELECTOR, '.name').text
    price = product.find_element(By.CSS_SELECTOR, '.price').text
    print(name)

<selenium.webdriver.remote.webelement.WebElement (session="c68c8b4931060e2192bacc437e4140bf", element="f.CC4F76A8EA840F66A7C8C08C70C15B2E.d.A3BD31A07D1CE8F2DF4D9338FDC6FCCE.e.4")>
키보드
<selenium.webdriver.remote.webelement.WebElement (session="c68c8b4931060e2192bacc437e4140bf", element="f.CC4F76A8EA840F66A7C8C08C70C15B2E.d.A3BD31A07D1CE8F2DF4D9338FDC6FCCE.e.5")>
마우스
<selenium.webdriver.remote.webelement.WebElement (session="c68c8b4931060e2192bacc437e4140bf", element="f.CC4F76A8EA840F66A7C8C08C70C15B2E.d.A3BD31A07D1CE8F2DF4D9338FDC6FCCE.e.6")>
모니터

##### 입력창 입력

In [10]:
keyword_input = driver.find_element(By.ID, 'keyword')
keyword_input.send_keys('USB');

In [11]:
keyword_input.clear()

In [12]:
keyword_input.send_keys('테슬라')

In [13]:
# 입력태그에서 텍스트 가져오기
keyword_str = driver.find_element(By.ID, 'keyword')

keyword_str.get_attribute('value')

'테슬라'

##### 버튼 클릭

In [14]:
button = driver.find_element(By.ID, 'search-btn')
button.click()

##### 명시적 대기

- 링크 클릭으로 다른 페이지 이동, 검색 후 결과 대기까지 시간이 소요
- `time.sleep(2)` 2초동안 대기 등의 파이썬 기본 함수가 제약사항이 많음
- 특정 조건이 만족할때까지 대기하는 로직 사용

In [15]:
# 명시적 대기를 위한 패키지 로드

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [17]:
# 여러 작업 수행 후

wait = WebDriverWait(driver, 10) # 10초 대기

title = wait.until(
    EC.presence_of_element_located((By.ID, 'title'))
)

title.text

'상품목록'

##### 데이터 가져오기

In [23]:
products = driver.find_elements(By.CLASS_NAME, 'product')

result = []

for product in products:
    name = product.find_element(By.CSS_SELECTOR, '.name').text
    price = product.find_element(By.CLASS_NAME, 'price').text

    result.append({'name': name, 'price': price})

In [24]:
result

[{'name': '키보드', 'price': '30000'},
 {'name': '마우스', 'price': '15000'},
 {'name': '모니터', 'price': '250000'}]

In [25]:
df = pd.DataFrame(result)
df

  name   price
0  키보드   30000
1  마우스   15000
2  모니터  250000

In [26]:
df.to_csv('../data/scrap_products.csv', encoding='utf-8')

##### 정리

- 웹 스크래핑시 필요요소
    - 웹드라이버로 웹사이트 오픈
    - 필요 요소 찾기
    - 입력태그 찾기
    - 버튼 요소 찾기
    - 입력하고 버튼 클릭해서 동작
    - 데이터 가져오기
    - 화면이 갱신되기까지 명시적 대기

#### 실습

##### 멜론 사이트 TOP100 스크래핑

In [2]:
# 페이지 전환없는 스크래핑용 패키지 로드

import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [22]:
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)
driver.get('https://www.melon.com/chart/index.htm')

company_name = wait. until(
    EC.presence_of_element_located((By.ID, 'footer'))
)

##### 차트의 곡 행 가져오기

In [ ]:
# CSS 선택자 입력시 태그 + .css 동일한 기능

songs = driver.find_elements(By.CSS_SELECTOR, 'tr.lst50, tr.lst100') # tr 붙여도 되고 안붙여도 됨

# len(songs)
for song in songs:
    # 노래순위
    rank = song.find_element(By.CSS_SELECTOR, '.rank').text
    # 노래제목
    title = song.find_element(By.CSS_SELECTOR, '.rank01 > span > a').text
    # 가수명
    singer = song.find_element(By.CSS_SELECTOR, '.rank02 a').text
    # 앨범명
    albumn = song.find_element(By.CSS_SELECTOR, '.rank03 a').text
    
    # 좋아요 개수
    like = song.find_element(By.CLASS_NAME, 'cnt').text

    print(rank, title, singer, albumn, like)

1 퇴사할게여 (Narr. 기안84) 소연 (SOYEON) 끝내주는 인생 39,490
2 LOVE ATTACK RESCENE (리센느) SCENEDROME 153,125
3 갑자기 아이오아이 (I.O.I) I.O.I 3rd MINI ALBUM [I.O.I : LOOP] 80,169
4 Deja Vu RESCENE (리센느) Dearest 58,925
5 Pretty Girl RESCENE (리센느) Pretty Girl - Special Single 66,146
6 REDRED CORTIS (코르티스) GREENGREEN 91,121
7 만찬가 태연 (TAEYEON) J-POP REMAKE Vol.1 49,646
8 BAD ATEEZ(에이티즈) GOLDEN HOUR : Part.5 33,775
9 BiiiG BIGBANG (빅뱅) BiiiG 56,948
10 LEMONADE aespa LEMONADE - The 2nd Album 59,585
11 Drowning WOODZ OO-LI 309,368
12 It′s Me 아일릿(ILLIT) MAMIHLAPINATAPAI 59,752
13 이 별로부터 아이유 이 별로부터 31,633
14 Good Goodbye 화사 (HWASA) Good Goodbye 125,780
15 Dear my crazy soulmate 아이유 이 별로부터 28,165
16 노스탈지아 BIG Naughty (서동현) 노스탈지아 32,563
17 사랑하게 될 거야 한로로 이상비행 149,804
18 RUDE! Hearts2Hearts (하츠투하츠) RUDE! 75,753
19 캐치 캐치 YENA (최예나) LOVE CATCHER 52,058
20 사랑은 늘 도망가 임영웅 신사와 아가씨 OST Part.2 241,223
21 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지 AKMU (악뮤) 항해 496,818
22 Popcorn 도경수(D.O.) 성장 - THE 3RD MINI ALBUM 94,924
23 생각을 멈추다 보면 최유리 생각을 멈추다 보면 50,892
24 0+0 한로로 자몽살구클럽 125,729
25 타임캡슐 다비치 타임캡슐 79,515
26 Skibidi 소녀시대-효리수 (Girls' Generation-HRS) Skibidi 17,096
27 너의 모든 순간 성시경 별에서 온 그대 OST Part.7 326,954
28 여름아 부탁해 볼빨간사춘기 여름아 부탁해 29,205
29 기쁨, 슬픔, 아름다운 마음 AKMU (악뮤) 개화 93,562
30 꿈꾸던 어른이 되었나요? 머무르 꿈꾸던 어른이 되었나요? 19,987
31 HOME SWEET HOME (feat. 태양, 대성) G-DRAGON HOME SWEET HOME (feat. 태양, 대성) 234,014
32 Pop Off Pop Off KiiiKiii (키키) WhyKiiiKiii 23,125
33 소문의 낙원 AKMU (악뮤) 개화 90,829
34 우리들의 블루스 임영웅 IM HERO 128,616
35 Lemon Tang Hearts2Hearts (하츠투하츠) Lemon Tang - The 2nd Mini Album 34,195
36 또또 임영웅 IM HERO 10 30,582
37 어제보다 슬픈 오늘 우디 (Woody) 어제보다 슬픈 오늘 91,176
38 순간을 영원처럼 임영웅 IM HERO 2 53,764
39 내게 사랑이 뭐냐고 물어본다면 로이킴 내게 사랑이 뭐냐고 물어본다면 102,971
40 Blue Valentine NMIXX Blue Valentine 121,634
41 천상연 이창섭 천상연 (웹툰 '선녀외전' X 이창섭 (LEE CHANGSUB)) 150,896
42 404 (New Era) KiiiKiii (키키) Delulu Pack 73,284
43 한 페이지가 될 수 있게 DAY6 (데이식스) The Book of Us : Gravity 371,540
44 toxic till the end 로제 (ROSÉ) rosie 162,241
45 BANG BANG IVE (아이브) REVIVE+ 69,091
46 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) 너드커넥션 (Nerd Connection) 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) 179,558
47 봄 내음보다 너를 김나영 봄 내음보다 너를 142,881
48 Runaway RESCENE (리센느) Runaway 35,667
49 부디 행복해질 것 임영웅 IM HERO 10 27,069
50 너에게 닿기를 10CM 너에게 닿기를 156,503
51 모르시나요(PROD.로코베리) 조째즈 모르시나요 111,091
52 오늘만 I LOVE YOU BOYNEXTDOOR 오늘만 I LOVE YOU 190,826
53 멸종위기사랑 이찬혁 EROS 106,835
54 모든 날, 모든 순간 (Every day, Every Moment) 폴킴 '키스 먼저 할까요?' OST Part.3 433,471
55 소나기 이클립스 (ECLIPSE) 선재 업고 튀어 OST Part 1 201,702
56 주저하는 연인들을 위해 잔나비 전설 454,336
57 뛰어(JUMP) BLACKPINK 뛰어(JUMP) 100,208
58 청춘만화 이무진 만화 (滿花) 107,811
59 Whiplash aespa Whiplash - The 5th Mini Album 156,410
60 HAPPY DAY6 (데이식스) Fourever 218,911
61 Guitarist 도경수(D.O.) DOPAMINE - The 4th Mini Album 16,078
62 Heavy Serenade NMIXX Heavy Serenade 56,248
63 Baila 임영웅 IM HERO 10 25,833
64 SWIM 방탄소년단 ARIRANG 64,571
65 이 밤을 빌려 말해요 PLAVE 이 밤을 빌려 말해요 (오늘 밤, 세계에서 이 사랑이 사라진다 해도 X PLAVE) 34,821
66 Seven (feat. Latto) - Clean Ver. 정국 Seven (feat. Latto) - Clean Ver. 233,900
67 모이세 임영웅 IM HERO 10 26,637
68 예뻤어 DAY6 (데이식스) Every DAY6 February 381,752
69 Golden HUNTR/X KPop Demon Hunters (Soundtrack from the Netflix Film) 193,577
70 그대 작은 나의 세상이 되어 카더가든 부재 88,932
71 헤어지자 말해요 박재정 1집 Alone 196,436
72 살아온 우리에게 임영웅 IM HERO 10 24,787
73 미워요 RE 임영웅 IM HERO 10 24,341
74 입춘 한로로 입춘 85,129
75 봄날 방탄소년단 YOU NEVER WALK ALONE 501,265
76 like JENNIE 제니 (JENNIE) Ruby 113,641
77 Love wins all 아이유 The Winning 226,754
78 Dynamite 방탄소년단 Dynamite (DayTime Version) 460,580
79 모래 알갱이 RE 임영웅 IM HERO 10 23,972
80 Die With A Smile Lady Gaga Die With A Smile 142,468
81 나는 반딧불 황가람 나는 반딧불 160,833
82 New York 임영웅 IM HERO 10 24,263
83 사랑은 늘 도망가 RE 임영웅 IM HERO 10 23,777
84 A Bientot RE 임영웅 IM HERO 10 23,757
85 첫 만남은 계획대로 되지 않아 TWS (투어스) Sparkling Blue 177,375
86 사랑인가 봐 멜로망스 사랑인가 봐 (사내맞선 OST 스페셜 트랙) 240,127
87 Welcome to the Show DAY6 (데이식스) Fourever 203,297
88 APT. 로제 (ROSÉ) APT. 222,605
89 다정히 내 이름을 부르면 경서예지 다정히 내 이름을 부르면 (경서예지 x 전건호) 225,993
90 Hype Boy NewJeans NewJeans 1st EP 'New Jeans' 318,218
91 Vitamin ME 프로미스나인 Glow ME 20,253
92 청혼하지 않을 이유를 못 찾았어 이무진 청혼하지 않을 이유를 못 찾았어 77,965
93 Less than a Lover 제니 (JENNIE) Less than a Lover 27,096
94 Magnetic 아일릿(ILLIT) SUPER REAL ME 149,305
95 Love Love Love (Feat. Yoong Jin Of Casker) 에픽하이 (EPIK HIGH) Remapping The Human Soul 129,848
96 STYLE Hearts2Hearts (하츠투하츠) STYLE 66,842
97 CRASH ALLDAY PROJECT CRASH 5,175
98 그댈 위한 멜로디 임영웅 IM HERO 2 42,729
99 REBEL HEART IVE (아이브) IVE EMPATHY 122,856
100 사랑은 봄비처럼...이별은 겨울비처럼... 임현정 All That Love 76,458

In [23]:
songs = driver.find_elements(By.CSS_SELECTOR, 'tr.lst50, tr.lst100')

datas = []

# len(songs)
for song in songs:
    # 노래순위
    rank = song.find_element(By.CSS_SELECTOR, '.rank').text
    # 노래제목
    title = song.find_element(By.CSS_SELECTOR, '.rank01 > span > a').text
    # 가수명
    singer = song.find_element(By.CSS_SELECTOR, '.rank02 a').text
    # 앨범명
    albumn = song.find_element(By.CSS_SELECTOR, '.rank03 a').text
    
    # 좋아요 개수
    like = song.find_element(By.CLASS_NAME, 'cnt').text

    # 단계상승하락
    rank_ud = song.find_element(By.CSS_SELECTOR, '.rank_wrap').get_attribute('title')

    datas.append({
        '순위' : rank,
        '순위변동' : rank_ud,
        '노래제목' : title,
        '가수' : singer,
        '앨범' : albumn,
        '좋아요' : like
    })

In [24]:
driver.quit()

In [25]:
df_melon100 = pd.DataFrame(datas)
df_melon100

,순위,순위변동,노래제목,가수,앨범,좋아요
0,1,순위 동일,퇴사할게여 (Narr. 기안84),소연 (SOYEON),끝내주는 인생,"39,518"
1,2,순위 동일,LOVE ATTACK,RESCENE (리센느),SCENEDROME,"153,146"
2,3,순위 동일,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],"80,176"
3,4,순위 동일,Deja Vu,RESCENE (리센느),Dearest,"58,937"
4,5,순위 동일,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,"66,158"
...,...,...,...,...,...,...
95,96,1단계 상승,New York,임영웅,IM HERO 10,"24,268"
96,97,2단계 상승,사랑은 봄비처럼...이별은 겨울비처럼...,임현정,All That Love,"76,461"
97,98,순위 동일,그댈 위한 멜로디,임영웅,IM HERO 2,"42,734"
98,99,7단계 하락,CRASH,ALLDAY PROJECT,CRASH,"5,224"
99,100,순위 동일,REBEL HEART,IVE (아이브),IVE EMPATHY,"122,858"

In [26]:
df_melon100.to_csv('../data/멜론TOP100_20261001_1300.csv', encoding='utf-8')